inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

# 基本的に自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - .git/*
    - bin/*
    - error_pages/**/*
    - db/schema.rb
    - db/fixtures/*
    - node_modules/**/*
    - lib/tasks/oneshot/archives/*
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  NewCops: disable

Style/Documentation:
  Enabled: false
