version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3030 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - 3030:3030
    depends_on:
      - db
    tty: true
  db:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27018:27017
